### ISSUE TITLE
ValueError("Unknown format '%s'" % format) error in quantify step.

### ISSUE THREAD

**Issue by drelo** [biobakery/shortbred#1]
Dear users, 

I wanted to used shortbread with a dataset of paired reads from several locations.
Following this tutorial https://github.com/biobakery/shortbred I managed to get my references ('marcadores.faa' to just differentiate it from the toy example). The markers were obtained considering the CARD database and the uniref database.

Now on Step 2 it gives me this error:

```
(shortbred) [andrespara@nagual SHORTBRED]$  ./shortbred-0.9.4/shortbred_quantify.py --markers marcadores.faa  --wgs AC-18_1.fq  --results exampleresults.txt --tmp example_quantify
Tested usearch. Appears to be working.
Treating input as a wgs file...
usearch v11.0.667_i86linux32, 4.0Gb RAM (264Gb total), 32 cores
(C) Copyright 2013-18 Robert C. Edgar, all rights reserved.
https://drive5.com/usearch

License: personal use only

00:00 41Mb    100.0% Reading mytestmarkers.faa
00:00 7.1Mb   100.0% Masking (fastamino)      
00:00 49Mb    100.0% Word stats         
00:00 49Mb    100.0% Alloc rows
00:01 49Mb    100.0% Build index
00:01 36Mb   Buffers (34 seqs)  
00:01 53Mb    100.0% Seqs

List of files in WGS set:AC-18_1.fq

List of files in WGS set (after unpacking tarfiles):AC-18_1.fq 

Working on file 1 of 1
Traceback (most recent call last):
  File "./shortbred-0.9.4/shortbred_quantify.py", line 522, in <module>
    for seq in SeqIO.parse(streamWGS, strFormat):
  File "/export/home/andrespara/miniconda3/envs/shortbred/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 609, in parse
    raise ValueError("Unknown format '%s'" % format)
ValueError: Unknown format 'unknown'

```

I also tried it with the uncompressed file.
The problem persist even against the example custom mymarkers.faa reference obtained following the tutorial Step 1. 

Here is a look of my fastq

```
@K00114:872:H25N2BBXY:2:1101:2311:1173 1:N:0:NCCAATAC
ACGCCAGTGGCTTTATCCTTGAATGTTTGGTTATCACCGAAACCGCTAGAAGCTTCCTCGATGTTTGGATTGATTGTGACATCAAAAGATTTCAAATCTTCAAACACATCAATCTCTGGAACGCCAGTATTGATTTTCTCGCTACTGTA
+
AAFFJJJFFFFFFJJFFFAJFFJJJ-FJJJF7FJJFFJJJJJJJJJJJJJFJJJAFJJJ<7FFFJ<FFFFJFFJJFF<JJJ<JJJJJJFFJJFJA<JJ<F-FJJFJJJFJFJJJJJJJJJFFFJJF-7A-7F-AFJJJFJFJJJJAFJJ
@K00114:872:H25N2BBXY:2:1101:2585:1191 1:N:0:NCCAATCT
GAAAACATCAAGTTTGAAGGCGCTCAATACCGCCAAGATATTGGCTACAGGGCGATTAAGGGCTAATGCCTTGCAGAACGCACGCGGGCTTAAACACTTTTGAAAATCTAGCGGTGTGATTGCCTATCCAACCGAGGCGATTTTTGGTT
+
<A<AFJJ<FAJFFJFFJJJJJJJJJAJJJJJJJJJ-F-<AFF<FJF<JFFJAFJ-7<JA-<-FJ7AAJJJJFAFF-FJJJAFJJJFJJJ-AFAFJ-7J7AF-AJAAJFJ<FJFF7AJJF-<AAJJJ7AFFJJJJJJJ7A-77A<-7AFF
@K00114:872:H25N2BBXY:2:1101:2788:1191 1:N:0:NCCAATAT
TAAATGCGGCGCTTCGCCGATTGCAGTTTTACCAGAAATCGAAATTTCAATGTGTTGAGAACAAGTTTGCTATCCAACATTTACACGAGGCGCTCGGCTGCTTGCGGGCGCGAACCAACAAGCGGGAGCTCCGCGGTGTTGAAGGAACA
```
I am using Fedora 32 and conda 4.8.3
I created a conda env solely for this program, here is the output of conda list.

```

# packages in environment at /export/home/andrespara/miniconda3/envs/shortbred:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
asn1crypto                1.3.0            py27h8c360ce_1    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.8.2                    py27_0  
biopython                 1.70                np112py27_1    bioconda
blas                      1.1                    openblas    conda-forge
blast                     2.9.0                h20b68b9_1    bioconda
boost                     1.68.0          py27h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
brotlipy                  0.7.0           py27h516909a_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cd-hit                    4.8.1                h8b12597_3    bioconda
certifi                   2019.11.28               py27_0    anaconda
cffi                      1.14.0           py27hd463f26_0    conda-forge
chardet                   3.0.4           py27h8c360ce_1006    conda-forge
conda                     4.8.3            py27h8c360ce_1    conda-forge
conda-build               3.18.11                  py27_0  
conda-package-handling    1.6.0            py27hdf8410d_2    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.8              py27h1ba5d50_0  
enum34                    1.1.10           py27h8c360ce_1    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gnutls                    3.6.13               h79a8f9a_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxml2                   2.9.10               he19cac6_1  
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
mmtf-python               1.1.2                      py_0    conda-forge
msgpack-python            1.0.0            py27h9e3301b_1    conda-forge
muscle                    3.8.1551             hc9558a2_5    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
numpy                     1.12.1          py27_blas_openblash1522bff_1001  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pillow                    6.2.1            py27hd70f55b_1    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.7.0            py27hdf8410d_1    conda-forge
py-lief                   0.9.0            py27he1b5a44_1    conda-forge
pycosat                   0.6.3           py27hdf8410d_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py27h8c360ce_1    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-libarchive-c       2.9                      py27_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py27hdf8410d_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
reportlab                 3.5.26           py27he686d34_0    anaconda
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
ruamel_yaml               0.15.80         py27hdf8410d_1001    conda-forge
scandir                   1.10.0           py27hdf8410d_1    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
soupsieve                 1.9.5                    py27_0  
sqlite                    3.32.3               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.47.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

```

Thanks for your help!

**Comment by drelo** [comment]
I rebuild a new conda environment and installed it again, I run the toy example with no problems. I should add that the program runs fine if I compare the ``` /shortbred-0.9.4/example/wgs.fna  ``` example file against my custom database. Here is a look at part of the output:

```
Family  Count   Hits    TotMarkerLength
gb|AAA03550.1|ARO:3002523|AAC(2)-Ia     0.0     0       178
gb|AAA16194.1|ARO:3002540|AAC(3)-VIa    0.0     0       299
gb|AAA16527.1|ARO:3002630|ANT(9)-Ia     0.0     0       243
gb|AAA19882.1|ARO:3003562|blaF  0.0     0       248
gb|AAA20116.1|ARO:3000180|tetA(P)       0.0     0       300
gb|AAA20117.1|ARO:3000195|tetB(P)       0.0     0       300
gb|AAA21532.1|ARO:3003559|cepA  0.0     0       290
gb|AAA21889.1|ARO:3002554|AAC(6)-Ig     0.0     0       58
gb|AAA22081.1|ARO:3004451|Agrobacterium 0.0     0       85
gb|AAA22277.1|ARO:3003007|bmr   0.0     0       300
gb|AAA22289.1|ARO:3002672|Bacillus      0.0     0       207
gb|AAA22562.1|ARO:3002878|BcII  0.0     0       205
gb|AAA22597.1|ARO:3000495|ErmD  0.0     0       206
gb|AAA22851.1|ARO:3000179|tet(L)        0.0     0       202
gb|AAA22904.1|ARO:3000578|CcrA  0.0     0       249
gb|AAA23018.1|ARO:3004454|Campylobacter 0.0     0       132
gb|AAA23033.2|ARO:3000190|tetO  0.0     0       236
gb|AAA23215.1|ARO:3002687|catQ  0.0     0       179
gb|AAA24786.1|ARO:3000368|vanC  0.0     0       245
gb|AAA25293.1|ARO:3000192|tetS  0.0     0       219
gb|AAA25334.1|ARO:3002543|AAC(3)-IXa    0.0     0       184
```

**Comment by luke-dt** [comment]
@drelo could you share an `environment.yml` of the environment you got this to work in? I'm having the same issue, and I can't tell if my dependencies are the incorrect version or something.

**Comment by drelo** [comment]
sorry @luke-dt I had to nuke the conda installation on that machine/cluster and that environment is lost.

**Comment by luke-dt** [comment]
:( RIP

**Comment by luke-dt** [comment]
I think I figured out the bug. Shortbred can't convert fastq to fasta and throws an error because it's expecting a .fna. If you give it a .fna file to begin with, it will work.
